spring.application.name=gateway-service
server.port=${PORT:8080}

eureka.client.service-url.defaultZone=https://eureka-1-oplc.onrender.com/eureka/


eureka.instance.prefer-ip-address=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=patients-service
spring.cloud.gateway.routes[0].uri=lb://patients-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/graphql/**, /graphiql/**

spring.cloud.gateway.routes[1].id=clinical-service
spring.cloud.gateway.routes[1].uri=lb://appointments-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/appointments/**, /api/v1/appointment_notes/**, /api/v1/appointment_cancels/**, /api/v1/appointment_receptions/**, /api/v1/appointment_status/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET, POST, PUT, DELETE, OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*