spring.application.name=veterinary
server.port=8084
#Postgres
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://localhost:5432/veterinary
spring.datasource.username=postgres
spring.datasource.password=eliseo18A$
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



# swagger-ui
springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled = true
springdoc.swagger-ui.path = /doc/swagger-ui.html
springdoc.packagesToScan=com.veterinary

#graphql http://localhost:8083/graphiql
spring.graphql.graphiql.enabled=true

security.jwt.secret-key = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 
# 1h en milisegundos 
security.jwt.expiration-time = 3600000