spring.application.name=graphql-service
server.port=8085
#Postgres
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://ep-still-grass-ah7zie95-pooler.c-3.us-east-1.aws.neon.tech/veterinary_main_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dmrx4shBAKe1
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# swagger-ui
springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled = true
springdoc.swagger-ui.path = /doc/swagger-ui.html
springdoc.packagesToScan=com.veterinary
#Others
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

#graphql http://localhost:8081/graphiql
spring.graphql.graphiql.enabled=true
#eureka
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=https://eureka-1-oplc.onrender.com/eureka/

